INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, manager_id, location_id)
VALUES (100, 'Marketing', 124, 1700);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, manager_id, location_id)
VALUES (102, 'Marketing', 124, 1700);

SELECT *
FROM DEPARTMENTS;

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (130, 'Test_name');

SELECT *
FROM DEPARTMENTS;

INSERT INTO DEPARTMENTS
VALUES (140, 'Test_name', null, null);

SELECT SYSDATE
      ,current_date
FROM dual;

INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION_ID)
VALUES (&department_id, '&department_name', &location);

--TABELUL trebuie sa existe
INSERT INTO TEST_EMP
SELECT *
FROM EMPLOYEES;

CREATE TABLE TEST_EMP AS
SELECT *
FROM EMPLOYEES;

SELECT *
FROM TEST_EMP;

truncate TABLE test_emp;

INSERT INTO TEST_EMP
SELECT
    *
FROM EMPLOYEES;

SELECT *
FROM TEST_EMP;

truncate TABLE test_emp;

INSERT INTO TEST_EMP
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;

SELECT *
FROM TEST_EMP;

--eroare - nu ajung valori
INSERT INTO TEST_EMP
SELECT employee_id, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;

--eroare - e-mail nu poate fi NULL
INSERT INTO TEST_EMP (EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID)
SELECT employee_id, LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;

--nu mai este eroare
INSERT INTO TEST_EMP (EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID, email, hire_date, job_id)
SELECT employee_id, LAST_NAME, DEPARTMENT_ID, 'NULL', sysdate, 'Ehh'
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;

UPDATE TEST_EMP
SET first_name = 'Nyna'
WHERE first_name = 'Neena';

SELECT *
FROM TEST_EMP;

UPDATE TEST_EMP
SET first_name = 'Nyna'
   ,salary = 50000
--WHERE first_name = 'Neena';
WHERE SALARY = 17000
AND DEPARTMENT_ID = 90;

SELECT *
FROM TEST_EMP;

DELETE FROM TEST_EMP
WHERE EMPLOYEE_ID IN (124,101, 102, 143, 144);

ROLLBACK;

SELECT *
FROM TEST_EMP;

COMMIT;

INSERT INTO TEST_EMP (EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID, email, hire_date, job_id)
SELECT employee_id, LAST_NAME, DEPARTMENT_ID, 'NULL', sysdate, 'Ehh'
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;

SELECT *
FROM TEST_EMP;

SAVEPOINT p1;

DELETE FROM TEST_EMP;

ROLLBACK TO SAVEPOINT p1;