SELECT 'a'
      ,'b'
      ,'c'
FROM dual
UNION ALL
select null
      ,'B'
      ,null
from dual;

SELECT
    *
FROM RETIRED_EMPLOYEES;

SELECT JOB_ID
FROM EMPLOYEES
UNION
SELECT JOB_ID
FROM RETIRED_EMPLOYEES;

SELECT JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
UNION ALL
SELECT JOB_ID, DEPARTMENT_ID
FROM RETIRED_EMPLOYEES
ORDER BY JOB_ID;

SELECT MANAGER_ID, DEPARTMENT_ID
FROM EMPLOYEES
INTERSECT
SELECT MANAGER_ID, DEPARTMENT_ID
FROM RETIRED_EMPLOYEES;

SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80
MINUS
SELECT EMPLOYEE_ID, JOB_ID
FROM RETIRED_EMPLOYEES
WHERE DEPARTMENT_ID = 90;

SELECT LOCATION_ID
      ,DEPARTMENT_NAME "Department"
      ,TO_CHAR(NULL) "Warehouse location"
FROM DEPARTMENTS
UNION
SELECT LOCATION_ID
      ,TO_CHAR(NULL) "Department"
      ,state_province
FROM LOCATIONS;
