--EX. 1
/*SELECT STUDENT_ID, NO_OF_DAYS_OFF
FROM AD_STUDENT_ATTENDANCE
WHERE NO_OF_DAYS_OFF > 15;  */

--ex. 2
/*SELECT COURSE_NAME, DEPARTMENT_ID
FROM AD_COURSE_DETAILS
WHERE COURSE_ID = 199; */

--ex. 3
/*SELECT STUDENT_ID, MARKS
FROM AD_EXAM_RESULTS
WHERE MARKS NOT BETWEEN 65 AND 90;*/

--ex. 4
--SELECT STUDENT_ID, FIRST_NAME, STUDENT_REG_YEAR
--FROM AD_STUDENT_DETAILS
--WHERE FIRST_NAME IN ('ROBERT', 'NINA')--('Robert', 'Nina')
--ORDER BY STUDENT_REG_YEAR;

--ex. 5
/*SELECT COURSE_NAME, DEPARTMENT_ID
FROM AD_COURSE_DETAILS
WHERE DEPARTMENT_ID IN (20,40)
ORDER BY COURSE_NAME;*/

--ex. 6
/*SELECT STUDENT_ID AS "Student #"
     , MARKS AS "Semester Marks"
FROM AD_EXAM_RESULTS
WHERE MARKS BETWEEN 65 AND 90
AND COURSE_ID IN (199, 189)*/

--ex. 7 var. 1
--SELECT FIRST_NAME, STUDENT_REG_YEAR
--FROM AD_STUDENT_DETAILS
--WHERE STUDENT_REG_YEAR BETWEEN '01.01.2014' AND '31.12.2014';

--ex. 7 var. 2
--SELECT FIRST_NAME, STUDENT_REG_YEAR
--FROM AD_STUDENT_DETAILS
--WHERE STUDENT_REG_YEAR LIKE '%14'

--ex. 8
--SELECT FIRST_NAME, PARENT_ID
--FROM AD_STUDENT_DETAILS
--WHERE EMAIL_ADDR IS NULL;

--ex. 9 var. 1
--SELECT FIRST_NAME, STUDENT_REG_YEAR, EMAIL_ADDR
--FROM AD_STUDENT_DETAILS
--WHERE EMAIL_ADDR IS NOT NULL
--ORDER BY STUDENT_REG_YEAR DESC, EMAIL_ADDR DESC;

--ex. 9 var. 2
--SELECT FIRST_NAME, STUDENT_REG_YEAR, EMAIL_ADDR
--FROM AD_STUDENT_DETAILS
--WHERE EMAIL_ADDR IS NOT NULL
--ORDER BY 2 DESC, 3 DESC;

--ex. 12
--SELECT FIRST_NAME
--FROM AD_STUDENT_DETAILS
--WHERE FIRST_NAME LIKE '_O%';

--ex. 13
SELECT FIRST_NAME
FROM AD_STUDENT_DETAILS
WHERE FIRST_NAME LIKE '%A%' AND FIRST_NAME LIKE '%N%';
